name: Build and Deploy Artifact

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      ARTIFACT_NAME: lambdaDeploymentArtifact
      CODE_DEPLOY_APPLICATION_NAME: csye6225-serverless
      CODEDEPLOY_APPLICATION_DEPLOYMENT_GROUP_NAME: csye6225-serverless-deployment
      CODEDEPLOY_DEPLOYMENT_CONFIG_NAME: CodeDeployDefault.LambdaAllAtOnce

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Create Lambda deployment artifact
        run:  |
              sudo mkdir codedeploy_artifact
              zip ${{env.ARTIFACT_NAME}} userVerification.js
              sudo mv ${{env.ARTIFACT_NAME}}.zip ./codedeploy_artifact

      - name: Configure AWS Credentials
        run:  |
          aws --version
          aws configure set aws_access_key_id ${{secrets.AWS_ACCESS_KEY}}
          aws configure set aws_secret_access_key ${{secrets.AWS_SECRET}}
          aws configure set default.region ${{env.AWS_REGION}}

      - name: Upload artifact to s3
        run: aws s3 sync ./codedeploy_artifact s3://${{secrets.AWS_S3_ARTIFACT_BUCKET_NAME}}

      - name: Update Lambda Function
        run: |
          aws lambda update-function-code --function-name userVerification --s3-bucket ${{secrets.AWS_S3_ARTIFACT_BUCKET_NAME}} --s3-key ${{env.ARTIFACT_NAME}}.zip --region us-east-1 > lambdaFile.txt
